import * as TEST_CONFIG from './config.testing'
import * as DEV_CONFIG from './config.development'

let REACT_APP_AUTH_LOGIN_ENDPOINT
let REACT_APP_AUTH_LOGOUT_ENDPOINT
let REACT_APP_AUTH_REFRESH_ENDPOINT
let REACT_APP_OAUTH_CLIENT_ID
let REACT_APP_OAUTH_AUTHORIZATION_URL
let REACT_APP_OAUTH_REDIRECT_URL
let REACT_APP_API_ME_ENDPOINT

if (process.env.NODE_ENV === 'test') {
  REACT_APP_AUTH_LOGIN_ENDPOINT = TEST_CONFIG.REACT_APP_AUTH_LOGIN_ENDPOINT
  REACT_APP_AUTH_LOGOUT_ENDPOINT = TEST_CONFIG.REACT_APP_AUTH_LOGOUT_ENDPOINT
  REACT_APP_AUTH_REFRESH_ENDPOINT = TEST_CONFIG.REACT_APP_AUTH_REFRESH_ENDPOINT
  REACT_APP_OAUTH_CLIENT_ID = TEST_CONFIG.REACT_APP_OAUTH_CLIENT_ID
  REACT_APP_OAUTH_AUTHORIZATION_URL = TEST_CONFIG.REACT_APP_OAUTH_AUTHORIZATION_URL
  REACT_APP_OAUTH_REDIRECT_URL = TEST_CONFIG.REACT_APP_OAUTH_REDIRECT_URL
  REACT_APP_API_ME_ENDPOINT = TEST_CONFIG.REACT_APP_API_ME_ENDPOINT
} else if (process.env.NODE_ENV === 'development') {
  REACT_APP_AUTH_LOGIN_ENDPOINT = DEV_CONFIG.REACT_APP_AUTH_LOGIN_ENDPOINT
  REACT_APP_AUTH_LOGOUT_ENDPOINT = DEV_CONFIG.REACT_APP_AUTH_LOGOUT_ENDPOINT
  REACT_APP_AUTH_REFRESH_ENDPOINT = DEV_CONFIG.REACT_APP_AUTH_REFRESH_ENDPOINT
  REACT_APP_OAUTH_CLIENT_ID = DEV_CONFIG.REACT_APP_OAUTH_CLIENT_ID
  REACT_APP_OAUTH_AUTHORIZATION_URL = DEV_CONFIG.REACT_APP_OAUTH_AUTHORIZATION_URL
  REACT_APP_OAUTH_REDIRECT_URL = DEV_CONFIG.REACT_APP_OAUTH_REDIRECT_URL
  REACT_APP_API_ME_ENDPOINT = DEV_CONFIG.REACT_APP_API_ME_ENDPOINT
}

export {
  REACT_APP_AUTH_LOGIN_ENDPOINT,
  REACT_APP_AUTH_LOGOUT_ENDPOINT,
  REACT_APP_AUTH_REFRESH_ENDPOINT,
  REACT_APP_OAUTH_CLIENT_ID,
  REACT_APP_OAUTH_AUTHORIZATION_URL,
  REACT_APP_OAUTH_REDIRECT_URL,
  REACT_APP_API_ME_ENDPOINT
}
